### ISSUE TITLE
Hey, I would like to talk to you

### ISSUE THREAD

**Issue by Swron** [s3pt3mb3r/SecretiveRendering#1]
I left you a star =) If you could add me on discord I would like to talk to you (! FlawzOfficial#9999)

**Comment by vxcall** [comment]
Hi, Thanks for the star man. That's literally fricking huge for me. :smile:
It seems you've set your preferences to deny friend requests on Discord so my request didn't reach you. Could you change your settings?

And I'm even not sure if there is anything I can do for you personally, please understand it. 😞

**Comment by Swron** [comment]
hey, I'm sorry I wasn't home last night, it's okay, I've changed my settings.
